(define (problem expert-logistic)
    (:domain expert-logistic)

    (:objects
p0 p1 p2 p3 p4 - persona
c0 c1 c2 c3 c4 - carga
b0 b1 b2 - asentamiento
b3 b4 b5 b6 b7 b8 b9 - almacen
r0 r1  - rover
)

(:init
(hay-camino b0 b4)
(hay-camino b0 b1)
(hay-camino b4 b8)
(hay-camino b1 b9)
(hay-camino b8 b6)
(hay-camino b9 b5)
(hay-camino b6 b7)
(hay-camino b4 b2)
(hay-camino b1 b3)
(hay-camino b2 b0)
(hay-camino b5 b7)
(hay-camino b6 b0)
(hay-camino b7 b9)
(hay-camino b9 b3)
(hay-camino b9 b2)
(hay-camino b6 b9)
(hay-camino b2 b1)
(hay-camino b8 b7)
(hay-camino b4 b7)
(hay-camino b1 b4)
(hay-camino b8 b5)
(hay-camino b8 b1)
(hay-camino b9 b4)
(aparcado-en r0 b2)
(aparcado-en r1 b5)
(esta-en p0 b1)
(esta-en p1 b0)
(esta-en p2 b0)
(esta-en p3 b1)
(esta-en p4 b1)
(esta-en c0 b3)
(esta-en c1 b6)
(esta-en c2 b9)
(esta-en c3 b7)
(esta-en c4 b5)
(= (current-capacity r0) 0)
(= (current-capacity r1) 0)
(= (gas-level r0) 12)
(= (gas-level r1) 18)
(= (sum-petitions) 0)
(low-petition p0 b1)
(important-petition p0 b2)
(low-petition c3 b2)
(medium-petition c3 b0)
(important-petition c3 b1)
(medium-petition c1 b1)
(important-petition c1 b0)
(important-petition c1 b2)
(important-petition p3 b0)
(low-petition p3 b1)
(low-petition c0 b1)
(low-petition c0 b0)
(important-petition p2 b2)
(low-petition p2 b1)
(important-petition p2 b0)
(low-petition p1 b0)
(low-petition p1 b2)
(medium-petition c2 b0)
(low-petition c2 b1)
(low-petition c4 b0)

)

(:goal
(and
(servido p0)
(servido c3)
(servido c1)
(servido p3)
(servido c0)
(servido p2)
(servido p1)
(servido c2)
(servido c4)

)
)
(:metric minimize
(- (* (sum-petitions) 3) (+(gas-level r0)  (gas-level r1) )))

)