(define (problem expert-logistic)
    (:domain expert-logistic)

    (:objects
p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - persona
c0 c1 c2 c3 c4 - carga
b0 b1 b2 b3 b4 b5 - asentamiento
b6 - almacen
r0 r1 r2  - rover
)

(:init
(hay-camino b2 b6)
(hay-camino b2 b1)
(hay-camino b6 b5)
(hay-camino b1 b0)
(hay-camino b6 b3)
(hay-camino b2 b4)
(hay-camino b6 b4)
(hay-camino b0 b2)
(hay-camino b6 b1)
(hay-camino b3 b5)
(hay-camino b4 b1)
(aparcado-en r0 b1)
(aparcado-en r1 b6)
(aparcado-en r2 b0)
(esta-en p0 b2)
(esta-en p1 b3)
(esta-en p2 b5)
(esta-en p3 b5)
(esta-en p4 b0)
(esta-en p5 b2)
(esta-en p6 b1)
(esta-en p7 b3)
(esta-en p8 b5)
(esta-en p9 b1)
(esta-en c0 b6)
(esta-en c1 b6)
(esta-en c2 b6)
(esta-en c3 b6)
(esta-en c4 b6)
(= (current-capacity r0) 0)
(= (current-capacity r1) 0)
(= (current-capacity r2) 0)
(= (gas-level r0) 14)
(= (gas-level r1) 7)
(= (gas-level r2) 10)
(= (sum-petitions b0) 0)
(= (sum-petitions b1) 0)
(= (sum-petitions b2) 0)
(= (sum-petitions b3) 0)
(= (sum-petitions b4) 0)
(= (sum-petitions b5) 0)
(= (sum-petitions b6) 0)
(important-petition p0 b5)
(low-petition p0 b4)
(important-petition p6 b5)
(low-petition p6 b3)
(low-petition p6 b1)
(important-petition p4 b4)
(medium-petition p7 b3)
(important-petition p1 b4)
(important-petition p1 b0)
(low-petition p1 b2)
(important-petition p0 b0)
(low-petition c0 b3)
(medium-petition p0 b1)
(medium-petition p3 b0)
(important-petition p3 b2)
(low-petition p8 b1)
(medium-petition p8 b2)
(important-petition p5 b2)
(important-petition p3 b4)
(important-petition p3 b5)
(important-petition p2 b1)
(important-petition p4 b0)
(important-petition p4 b1)
(important-petition p4 b5)
(low-petition p9 b5)

)

(:goal
(and
(or (esta-en p0 b5) (esta-en p0 b4) )
(or (esta-en p6 b5) (esta-en p6 b3) (esta-en p6 b1) )
(esta-en c4 b4)
(esta-en p7 b3)
(or (esta-en p1 b4) (esta-en p1 b0) (esta-en p1 b2) )
(or (esta-en c0 b0) (esta-en c0 b3) (esta-en c0 b1) )
(or (esta-en c3 b0) (esta-en c3 b2) )
(or (esta-en p8 b1) (esta-en p8 b2) )
(esta-en p5 b2)
(or (esta-en p3 b4) (esta-en p3 b5) )
(esta-en c2 b1)
(or (esta-en p4 b0) (esta-en p4 b1) (esta-en p4 b5) )
(esta-en p9 b5)

)
)
(:metric maximize
(+ (+ (+ (+ (+ (+ (sum-petitions b0)  (sum-petitions b1) ) (sum-petitions b2) ) (sum-petitions b3) ) (sum-petitions b4) ) (sum-petitions b5) ) (sum-petitions b6) ))

)